# Generated by Django 5.2.15 on 2026-06-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Назва типу')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Ідентифікатор')),
            ],
            options={
                'verbose_name': 'Тип простору',
                'verbose_name_plural': 'Типи простору',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Кімната / місце', 'verbose_name_plural': 'Кімнати / місця'},
        ),
        migrations.AlterModelOptions(
            name='roomfeature',
            options={'verbose_name': 'Особливість', 'verbose_name_plural': 'Особливості'},
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступна для бронювання'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='Завершення'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.room', verbose_name='Кімната'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=120, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Вмістимість, осіб'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за годину'),
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Особливість'),
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bookings.room', verbose_name='Кімната'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='bookings.roomtype', verbose_name='Тип'),
        ),
    ]
